version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Etc/Greenwich
  ignore:
  - dependency-name: "@zendeskgarden/css-buttons"
    versions:
    - "> 6.1.2"
  - dependency-name: airtable
    versions:
    - 0.10.1
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
