name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Install dependencies
      run: script/bootstrap
    - name: Run tests
      run: script/test
    - name: Run build
      run: script/build
